In [1]:
# Colab cell 1
!pip install biopython pandas tqdm openpyxl
!pip install -q condacolab
import condacolab
condacolab.install()

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 56.8 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.87
⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:10
🔁 Restarting kernel...

In [1]:
# Colab cell 2
!conda install -c bioconda -c conda-forge ncbi-amrfinderplus blast prodigal -y
!amrfinder_update

Channels:
 - bioconda
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
Solving environment: - \ | / done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - blast
    - ncbi-amrfinderplus
    - prodigal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blast-2.17.0               |       h66d330f_0        80.9 MB  bioconda
    c-ares-1.34.6              |       hb03c661_0         203 KB  conda-forge
    ca-certificates-2026.4.22  |       hbd8a1cb_0         128 KB  conda-forge
    certifi-2026.4.22          |     pyhd8ed1ab_0         132 KB  conda-forge
    conda-24.11.3              |  py311h38be061_0         1.1 MB  conda-forge
    curl-8.18.0                |       h4e3cde8_0         186 KB  conda-forge
    entrez-direct-24.0         |       he881be0_0        16.3 MB  bioconda
    gsl-2.7                    |       he838d99_0         3.2 MB  conda-forge
    hmmer-3.4                  |       hb6cb901_4        11.4 MB  bioconda
    libblas-3.9.0              |31_h59b9bed_openblas          16 KB  conda-forge
    libcblas-3.9.0             |31_he106b2a_openblas          16 KB  conda-forge
    libcurl-8.18.0             |       h4e3cde8_0         452 KB  conda-forge
    libgfortran-14.2.0         |       h69a702a_2          52 KB  conda-forge
    libgfortran-ng-14.2.0      |       h69a702a_2          53 KB  conda-forge
    libgfortran5-14.2.0        |       hf1ad2bd_2         1.4 MB  conda-forge
    libidn2-2.3.8              |       hfac485b_1         136 KB  conda-forge
    libnghttp2-1.68.1          |       h877daf1_0         648 KB  conda-forge
    libopenblas-0.3.29         |pthreads_h94d23a6_0         5.6 MB  conda-forge
    libsqlite-3.52.0           |       h0c1763c_0         928 KB  conda-forge
    libunistring-0.9.10        |       h7f98852_0         1.4 MB  conda-forge
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    ncbi-amrfinderplus-4.2.7   |       hf69ffd2_0         1.3 MB  bioconda
    ncbi-vdb-3.4.1             |       hd63eeec_0         8.8 MB  bioconda
    openmpi-4.1.6              |     hc5af2df_101         3.9 MB  conda-forge
    openssl-3.6.2              |       h35e630c_0         3.0 MB  conda-forge
    pcre2-10.47                |       haa7fec5_0         1.2 MB  conda-forge
    perl-5.32.1                | 7_hd590300_perl5        12.7 MB  conda-forge
    perl-archive-tar-3.04      | pl5321hdfd78af_0          34 KB  bioconda
    perl-carp-1.38             | pl5321hdfd78af_4          17 KB  bioconda
    perl-common-sense-3.75     | pl5321hdfd78af_0          13 KB  bioconda
    perl-compress-raw-bzip2-2.214| pl5321hda65f42_0          54 KB  conda-forge
    perl-compress-raw-zlib-2.214| pl5321h4dac143_0          79 KB  conda-forge
    perl-encode-3.19           | pl5321hec16e2b_1         2.1 MB  bioconda
    perl-exporter-5.72         | pl5321hdfd78af_2          16 KB  bioconda
    perl-exporter-tiny-1.002002| pl5321hdfd78af_0          25 KB  bioconda
    perl-extutils-makemaker-7.70| pl5321hd8ed1ab_0         154 KB  conda-forge
    perl-io-compress-2.216     | pl5321h503566f_0          85 KB  bioconda
    perl-io-zlib-1.15          | pl5321hdfd78af_1          12 KB  bioconda
    perl-json-4.11             | pl5321hdfd78af_0          52 KB  bioconda
    perl-json-xs-4.04          | pl5321h9948957_0          69 KB  bioconda
    perl-list-moreutils-0.430  | pl5321hdfd78af_0          32 KB  bioconda
    perl-list-moreutils-xs-0.430| pl5321h7b50bb2_5          50 KB  bioconda
    perl-parent-0.236          | pl5321hdfd78af_2           8 KB  bioconda
    perl-pathtools-3.75        | pl5321hec16e2b_3          42 KB  bioconda
    perl-scalar-list-utils-1.62| pl5321hec16e2b_1          44 KB  bioconda
    perl-types-serialiser-1.01 | pl5321hdfd78af_0          13 KB  bioconda
    prodigal-2.6.3             |      h577a1d6_11         588 KB  bioconda
    wget-1.25.0                |       h653f8fd_1         729 KB  conda-forge
    zlib-1.3.1                 |       hb9d3cd8_2          90 KB  conda-forge
    zstandard-0.25.0           |  py311haee01d2_1         456 KB  conda-forge
    zstd-1.5.7                 |       hb78ec9c_6         587 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       160.4 MB

The following NEW packages will be INSTALLED:

  blast              bioconda/linux-64::blast-2.17.0-h66d330f_0
  curl               conda-forge/linux-64::curl-8.18.0-h4e3cde8_0
  entrez-direct      bioconda/linux-64::entrez-direct-24.0-he881be0_0
  gsl                conda-forge/linux-64::gsl-2.7-he838d99_0
  hmmer              bioconda/linux-64::hmmer-3.4-hb6cb901_4
  libblas            conda-forge/linux-64::libblas-3.9.0-31_h59b9bed_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-31_he106b2a_openblas
  libgfortran        conda-forge/linux-64::libgfortran-14.2.0-h69a702a_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-14.2.0-h69a702a_2
  libgfortran5       conda-forge/linux-64::libgfortran5-14.2.0-hf1ad2bd_2
  libidn2            conda-forge/linux-64::libidn2-2.3.8-hfac485b_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.29-pthreads_h94d23a6_0
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0
  mpi                conda-forge/linux-64::mpi-1.0-openmpi
  ncbi-amrfinderplus bioconda/linux-64::ncbi-amrfinderplus-4.2.7-hf69ffd2_0
  ncbi-vdb           bioconda/linux-64::ncbi-vdb-3.4.1-hd63eeec_0
  openmpi            conda-forge/linux-64::openmpi-4.1.6-hc5af2df_101
  pcre2              conda-forge/linux-64::pcre2-10.47-haa7fec5_0
  perl               conda-forge/linux-64::perl-5.32.1-7_hd590300_perl5
  perl-archive-tar   bioconda/noarch::perl-archive-tar-3.04-pl5321hdfd78af_0
  perl-carp          bioconda/noarch::perl-carp-1.38-pl5321hdfd78af_4
  perl-common-sense  bioconda/noarch::perl-common-sense-3.75-pl5321hdfd78af_0
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-bzip2-2.214-pl5321hda65f42_0
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-zlib-2.214-pl5321h4dac143_0
  perl-encode        bioconda/linux-64::perl-encode-3.19-pl5321hec16e2b_1
  perl-exporter      bioconda/noarch::perl-exporter-5.72-pl5321hdfd78af_2
  perl-exporter-tiny bioconda/noarch::perl-exporter-tiny-1.002002-pl5321hdfd78af_0
  perl-extutils-mak~ conda-forge/noarch::perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0
  perl-io-compress   bioconda/linux-64::perl-io-compress-2.216-pl5321h503566f_0
  perl-io-zlib       bioconda/noarch::perl-io-zlib-1.15-pl5321hdfd78af_1
  perl-json          bioconda/noarch::perl-json-4.11-pl5321hdfd78af_0
  perl-json-xs       bioconda/linux-64::perl-json-xs-4.04-pl5321h9948957_0
  perl-list-moreuti~ bioconda/noarch::perl-list-moreutils-0.430-pl5321hdfd78af_0
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-xs-0.430-pl5321h7b50bb2_5
  perl-parent        bioconda/noarch::perl-parent-0.236-pl5321hdfd78af_2
  perl-pathtools     bioconda/linux-64::perl-pathtools-3.75-pl5321hec16e2b_3
  perl-scalar-list-~ bioconda/linux-64::perl-scalar-list-utils-1.62-pl5321hec16e2b_1
  perl-types-serial~ bioconda/noarch::perl-types-serialiser-1.01-pl5321hdfd78af_0
  prodigal           bioconda/linux-64::prodigal-2.6.3-h577a1d6_11
  wget               conda-forge/linux-64::wget-1.25.0-h653f8fd_1
  zlib               conda-forge/linux-64::zlib-1.3.1-hb9d3cd8_2

The following packages will be UPDATED:

  c-ares                                  1.34.4-hb9d3cd8_0 --> 1.34.6-hb03c661_0
  ca-certificates    conda-forge/linux-64::ca-certificates~ --> conda-forge/noarch::ca-certificates-2026.4.22-hbd8a1cb_0
  certifi                           2024.12.14-pyhd8ed1ab_0 --> 2026.4.22-pyhd8ed1ab_0
  conda                             24.11.2-py311h38be061_1 --> 24.11.3-py311h38be061_0
  libcurl                                 8.11.1-h332b0f4_0 --> 8.18.0-h4e3cde8_0
  libnghttp2                              1.64.0-h161d5f1_0 --> 1.68.1-h877daf1_0
  libsqlite                               3.47.2-hee588c1_0 --> 3.52.0-h0c1763c_0
  openssl                                  3.4.0-h7b32b05_1 --> 3.6.2-h35e630c_0
  zstandard                          0.23.0-py311hbc35293_1 --> 0.25.0-py311haee01d2_1
  zstd                                     1.5.6-ha6fb4c9_0 --> 1.5.7-hb78ec9c_6



Downloading and Extracting Packages:
blast-2.17.0         | 80.9 MB   | :   0% 0/1 [00:00<?, ?it/s]
entrez-direct-24.0   | 16.3 MB   | :   0% 0/1 [00:00<?, ?it/s]

perl-5.32.1          | 12.7 MB   | :   0% 0/1 [00:00<?, ?it/s]


hmmer-3.4            | 11.4 MB   | :   0% 0/1 [00:00<?, ?it/s]



ncbi-vdb-3.4.1       | 8.8 MB    | :   0% 0/1 [00:00<?, ?it/s]




libopenblas-0.3.29   | 5.6 MB    | :   0% 0/1 [00:00<?, ?it/s]





openmpi-4.1.6        | 3.9 MB    | :   0% 0/1 [00:00<?, ?it/s]






gsl-2.7              | 3.2 MB    | :   0% 0/1 [00:00<?, ?it/s]







openssl-3.6.2        | 3.0 MB    | :   0% 0/1 [00:00<?, ?it/s]








perl-encode-3.19     | 2.1 MB    | :   0% 0/1 [00:00<?, ?it/s]









libgfortran5-14.2.0  | 1.4 MB    | :   0% 0/1 [00:00<?, ?it/s]










libunistring-0.9.10  | 1.4 MB    | :   0% 0/1 [00:00<?, ?it/s]











ncbi-amrfinderplus-4 | 1.3 MB    | :   0% 0/1 [00:00<?, ?it/s]












pcre2-10.47          | 1.2 MB    | :   0% 0/1 [00:00<?, ?it/s]













conda-24.11.3        | 1.1 MB    | :   0% 0/1 [00:00<?, ?it/s]














libsqlite-3.52.0     | 928 KB    | :   0% 0/1 [00:00<?, ?it/s]















wget-1.25.0          | 729 KB    | :   0% 0/1 [00:00<?, ?it/s]
















libnghttp2-1.68.1    | 648 KB    | :   0% 0/1 [00:00<?, ?it/s]

















prodigal-2.6.3       | 588 KB    | :   0% 0/1 [00:00<?, ?it/s]


















blast-2.17.0         | 80.9 MB   | :   1% 0.0054077490424966354/1 [00:00<00:18, 18.57s/it]
entrez-direct-24.0   | 16.3 MB   | :   3% 0.025828670426730545/1 [00:00<00:03,  3.89s/it]


hmmer-3.4            | 11.4 MB   | :   0% 0.0013752217507301458/1 [00:00<01:14, 74.23s/it]

perl-5.32.1          | 12.7 MB   | :   0% 0.0012277751453917628/1 [00:00<01:26, 87.07s/it]



blast-2.17.0         | 80.9 MB   | :   5% 0.05214615148121756/1 [00:00<00:03,  3.41s/it]
entrez-direct-24.0   | 16.3 MB   | :  24% 0.2439374429191218/1 [00:00<00:00,  1.37it/s]


hmmer-3.4            | 11.4 MB   | :   8% 0.07701241804088817/1 [00:00<00:02,  2.25s/it]

perl-5.32.1          | 12.7 MB   | :  21% 0.2050384492804244/1 [00:00<00:00,  1.17it/s]



blast-2.17.0         | 80.9 MB   | :   9% 0.09424934045494136/1 [00:00<00:02,  2.85s/it]
entrez-direct-24.0   | 16.3 MB   | :  43% 0.4304778404455091/1 [00:00<00:00,  1.59it/s]

perl-5.32.1          | 12.7 MB   | :  46% 0.4591879043765193/1 [00:00<00:00,  1.79it/s]


hmmer-3.4            | 11.4 MB   | :  35% 0.3451806594332666/1 [00:00<00:00,  1.45it/s]



blast-2.17.0         | 80.9 MB   | :  14% 0.13944267173866326/1 [00:00<00:02,  2.56s/it]
entrez-direct-24.0   | 16.3 MB   | :  64% 0.6409336735522024/1 [00:00<00:00,  1.79it/s]

perl-5.32.1          | 12.7 MB   | :  75% 0.7501706138343671/1 [00:00<00:00,  2.22it/s]


blast-2.17.0         | 80.9 MB   | :  18% 0.18424973523363536/1 [00:00<00:01,  2.45s/it]
entrez-direct-24.0   | 16.3 MB   | :  87% 0.8714784725463528/1 [00:00<00:00,  1.97it/s]


hmmer-3.4            | 11.4 MB   | :  93% 0.9324003469950389/1 [00:00<00:00,  2.29it/s]



blast-2.17.0         | 80.9 MB   | :  23% 0.2251941208411099/1 [00:00<00:01,  2.45s/it]




libopenblas-0.3.29   | 5.6 MB    | :   0% 0.0027679004637044184/1 [00:00<03:47, 227.90s/it]




blast-2.17.0         | 80.9 MB   | :  27% 0.26613850644858444/1 [00:00<00:02,  2.99s/it]

perl-5.32.1          | 12.7 MB   | : 100% 1.0/1 [00:00<00:00,  1.09it/s]

perl-5.32.1          | 12.7 MB   | : 100% 1.0/1 [00:00<00:00,  1.09it/s]




libopenblas-0.3.29   | 5.6 MB    | :  61% 0.6144739029423809/1 [00:00<00:00,  1.05it/s]


blast-2.17.0         | 80.9 MB   | :  30% 0.3016751430135623/1 [00:00<00:02,  3.35s/it]






gsl-2.7              | 3.2 MB    | :   0% 0.00485247257230507/1 [00:00<03:10, 191.60s/it]






blast-2.17.0         | 80.9 MB   | :  33% 0.3333491016910426/1 [00:01<00:02,  3.60s/it]




libopenblas-0.3.29   | 5.6 MB    | : 100% 1.0/1 [00:01<00:00,  1.30it/s]




libopenblas-0.3.29   | 5.6 MB    | : 100% 1.0/1 [00:01<00:00,  1.30it/s]
entrez-direct-24.0   | 16.3 MB   | : 100% 1.0/1 [00:01<00:00,  1.97it/s]







openssl-3.6.2        | 3.0 MB    | :   1% 0.005173188460480711/1 [00:01<03:32, 214.03s/it]






gsl-2.7              | 3.2 MB    | : 100% 1.0/1 [00:01<00:00,  1.07s/it]








blast-2.17.0         | 80.9 MB   | :  37% 0.372941550037893/1 [00:01<00:02,  3.26s/it]









blast-2.17.0         | 80.9 MB   | :  41% 0.4140790695397424/1 [00:01<00:01,  3.00s/it]








perl-encode-3.19     | 2.1 MB    | : 100% 1.0/1 [00:01<00:00,  1.09it/s]








perl-encode-3.19     | 2.1 MB    | : 100% 1.0/1 [00:01<00:00,  1.09it/s]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:01<00:00,  1.08it/s]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:01<00:00,  1.08it/s]









libgfortran5-14.2.0  | 1.4 MB    | : 100% 1.0/1 [00:01<00:00, 105.34s/it]










libunistring-0.9.10  | 1.4 MB    | :   1% 0.011429878976110548/1 [00:01<01:52, 113.60s/it]












blast-2.17.0         | 80.9 MB   | :  46% 0.4619762753447126/1 [00:01<00:01,  2.68s/it]










libunistring-0.9.10  | 1.4 MB    | : 100% 1.0/1 [00:01<00:00, 113.60s/it]











ncbi-amrfinderplus-4 | 1.3 MB    | :   1% 0.012166098732227761/1 [00:01<01:54, 115.45s/it]













conda-24.11.3        | 1.1 MB    | :   1% 0.01364371451460054/1 [00:01<01:42, 103.75s/it]












pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:01<00:00, 99.82s/it]





blast-2.17.0         | 80.9 MB   | :  50% 0.5007961881140635/1 [00:01<00:01,  2.74s/it]














libsqlite-3.52.0     | 928 KB    | :   2% 0.017249166441190806/1 [00:01<01:23, 85.07s/it]













conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:01<00:00, 103.75s/it]











ncbi-amrfinderplus-4 | 1.3 MB    | : 100% 1.0/1 [00:01<00:00,  1.10s/it]











ncbi-amrfinderplus-4 | 1.3 MB    | : 100% 1.0/1 [00:01<00:00,  1.10s/it]














libsqlite-3.52.0     | 928 KB    | : 100% 1.0/1 [00:01<00:00, 85.07s/it]















blast-2.17.0         | 80.9 MB   | :  54% 0.538457297517165/1 [00:01<00:01,  2.74s/it]
















libnghttp2-1.68.1    | 648 KB    | :   2% 0.024699100315974817/1 [00:01<01:01, 63.18s/it]















wget-1.25.0          | 729 KB    | : 100% 1.0/1 [00:01<00:00, 70.18s/it]
















libnghttp2-1.68.1    | 648 KB    | : 100% 1.0/1 [00:01<00:00, 63.18s/it]


















 ... (more hidden) ...


















 ... (more hidden) ...





blast-2.17.0         | 80.9 MB   | :  61% 0.6054747588652483/1 [00:01<00:00,  2.23s/it]





blast-2.17.0         | 80.9 MB   | :  65% 0.6512474918320948/1 [00:01<00:00,  2.39s/it]

















blast-2.17.0         | 80.9 MB   | :  69% 0.6941232163833182/1 [00:01<00:00,  2.46s/it]

















prodigal-2.6.3       | 588 KB    | :  79% 0.789283436104614/1 [00:01<00:00,  1.76s/it]





openmpi-4.1.6        | 3.9 MB    | :  44% 0.43882493552242563/1 [00:01<00:01,  2.45s/it]

















blast-2.17.0         | 80.9 MB   | :  74% 0.7356470036739173/1 [00:02<00:00,  2.99s/it]





blast-2.17.0         | 80.9 MB   | :  80% 0.8028575989163755/1 [00:02<00:00,  3.60s/it]



blast-2.17.0         | 80.9 MB   | :  83% 0.8322139508613573/1 [00:02<00:00,  3.56s/it]





blast-2.17.0         | 80.9 MB   | :  96% 0.9560127771556552/1 [00:02<00:00,  3.32s/it]





blast-2.17.0         | 80.9 MB   | : 100% 0.998309100023754/1 [00:03<00:00,  2.98s/it]





openmpi-4.1.6        | 3.9 MB    | : 100% 1.0/1 [00:03<00:00,  2.10s/it]





blast-2.17.0         | 80.9 MB   | : 100% 1.0/1 [00:03<00:00,  2.98s/it]

perl-5.32.1          | 12.7 MB   | : 100% 1.0/1 [00:04<00:00,  1.09it/s]




libopenblas-0.3.29   | 5.6 MB    | : 100% 1.0/1 [00:05<00:00,  1.30it/s]


hmmer-3.4            | 11.4 MB   | : 100% 1.0/1 [00:07<00:00,  2.29it/s]






gsl-2.7              | 3.2 MB    | : 100% 1.0/1 [00:09<00:00,  1.07s/it]
entrez-direct-24.0   | 16.3 MB   | : 100% 1.0/1 [00:09<00:00,  1.97it/s]








perl-encode-3.19     | 2.1 MB    | : 100% 1.0/1 [00:09<00:00,  1.09it/s]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:09<00:00,  1.08it/s]









libgfortran5-14.2.0  | 1.4 MB    | : 100% 1.0/1 [00:09<00:00,  9.47s/it]









libgfortran5-14.2.0  | 1.4 MB    | : 100% 1.0/1 [00:09<00:00,  9.47s/it]












pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:09<00:00,  9.63s/it]












pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:09<00:00,  9.63s/it]













conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:10<00:00,  9.91s/it]













conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:10<00:00,  9.91s/it]










libunistring-0.9.10  | 1.4 MB    | : 100% 1.0/1 [00:10<00:00,  9.95s/it]










libunistring-0.9.10  | 1.4 MB    | : 100% 1.0/1 [00:10<00:00,  9.95s/it]














libsqlite-3.52.0     | 928 KB    | : 100% 1.0/1 [00:10<00:00,  9.96s/it]














libsqlite-3.52.0     | 928 KB    | : 100% 1.0/1 [00:10<00:00,  9.96s/it]











ncbi-amrfinderplus-4 | 1.3 MB    | : 100% 1.0/1 [00:10<00:00,  1.10s/it]















wget-1.25.0          | 729 KB    | : 100% 1.0/1 [00:10<00:00, 10.07s/it]















wget-1.25.0          | 729 KB    | : 100% 1.0/1 [00:10<00:00, 10.07s/it]
















libnghttp2-1.68.1    | 648 KB    | : 100% 1.0/1 [00:10<00:00, 10.08s/it]
















libnghttp2-1.68.1    | 648 KB    | : 100% 1.0/1 [00:10<00:00, 10.08s/it]


















 ... (more hidden) ...


















 ... (more hidden) ...

















prodigal-2.6.3       | 588 KB    | : 100% 1.0/1 [00:11<00:00,  1.76s/it]





blast-2.17.0         | 80.9 MB   | : 100% 1.0/1 [00:16<00:00,  2.98s/it]























































































































































































































































































































































































































































Preparing transaction: - \ | done
Verifying transaction: - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
Executing transaction: - \ | / - \ | / - \ | / - \ | / - \ |
For Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default.
To enable it, please set the environment variable OMPI_MCA_opal_cuda_support=true before
launching your MPI processes. Equivalently, you can set the MCA parameter in the command line:
mpiexec --mca opal_cuda_support 1 ...

In addition, the UCX support is also built but disabled by default.
To enable it, first install UCX (conda install -c conda-forge ucx). Then, set the environment
variables OMPI_MCA_pml="ucx" OMPI_MCA_osc="ucx" before launching your MPI processes.
Equivalently, you can set the MCA parameters in the command line:
mpiexec --mca pml ucx --mca osc ucx ...
Note that you might also need to set UCX_MEMTYPE_CACHE=n for CUDA awareness via UCX.
Please consult UCX's documentation for detail.


/ - \ | / - \ | / - \ | / - done
Running: amrfinder_update

In [2]:
# Colab cell 4
import os, glob, subprocess, pandas as pd
from tqdm import tqdm

os.makedirs("amrfinder_results", exist_ok=True)

fasta_files = glob.glob("isolates/*")

for fasta in tqdm(fasta_files):
    sample = os.path.basename(fasta).split(".")[0]
    out_file = f"amrfinder_results/{sample}_amrfinder.tsv"

    cmd = [
        "amrfinder",
        "-n", fasta,
        "-o", out_file
    ]

    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        print(f"AMRFinder failed for {sample}: {e}")

print("Done.")

0it [00:00, ?it/s]

Done.

In [3]:
# Colab cell 5
import pandas as pd, glob, os

all_results = []

for file in glob.glob("amrfinder_results/*_amrfinder.tsv"):
    sample = os.path.basename(file).replace("_amrfinder.tsv", "")

    if os.path.getsize(file) == 0:
        continue

    df = pd.read_csv(file, sep="\t")
    df["isolate_id"] = sample
    all_results.append(df)

if all_results:
    amr_df = pd.concat(all_results, ignore_index=True)
else:
    amr_df = pd.DataFrame()

amr_df.head()

Empty DataFrame
Columns: []
Index: []

In [4]:
# Colab cell 6
print(amr_df.columns.tolist())

# Try to standardize common AMRFinderPlus columns
keep_cols = []

for col in [
    "isolate_id",
    "Gene symbol",
    "Sequence name",
    "Scope",
    "Element type",
    "Element subtype",
    "Class",
    "Subclass",
    "Method",
    "% Identity",
    "% Coverage of reference sequence",
    "Start",
    "Stop",
    "Strand"
]:
    if col in amr_df.columns:
        keep_cols.append(col)

amr_summary = amr_df[keep_cols].copy()
amr_summary.head()

[]

Empty DataFrame
Columns: []
Index: []

In [5]:
# Colab cell 7
priority_genes = [
    "blaKPC", "blaNDM", "blaOXA", "blaVIM", "blaIMP",
    "mcr", "mecA", "vanA", "vanB", "aac", "aph", "erm", "tet"
]

def is_priority_gene(gene):
    gene = str(gene).lower()
    return any(pg.lower() in gene for pg in priority_genes)

gene_col = "Gene symbol" if "Gene symbol" in amr_summary.columns else amr_summary.columns[1]

amr_summary["priority_marker"] = amr_summary[gene_col].apply(is_priority_gene)

amr_summary.sort_values(["isolate_id", "priority_marker"], ascending=[True, False]).head(20)

IndexError: index 1 is out of bounds for axis 0 with size 0

In [6]:
# SAFE Cell 7: Flag clinically important AMR genes

priority_genes = [
    "blaKPC", "blaNDM", "blaOXA", "blaVIM", "blaIMP",
    "mcr", "mecA", "vanA", "vanB", "aac", "aph", "erm", "tet"
]

if amr_summary.empty:
    print("⚠️ amr_summary is empty.")
    print("This means AMRFinderPlus did not return/load any AMR hits.")
    print("Check the previous AMRFinder result files first.")
else:
    print("Columns available:")
    print(amr_summary.columns.tolist())

    gene_col = "Gene symbol" if "Gene symbol" in amr_summary.columns else None

    if gene_col is None:
        possible_gene_cols = [
            c for c in amr_summary.columns
            if "gene" in c.lower() or "symbol" in c.lower() or "element" in c.lower()
        ]
        print("Possible gene columns:", possible_gene_cols)

        if possible_gene_cols:
            gene_col = possible_gene_cols[0]
        else:
            raise ValueError("No gene-like column found in AMR summary.")

    def is_priority_gene(gene):
        gene = str(gene).lower()
        return any(pg.lower() in gene for pg in priority_genes)

    amr_summary["priority_marker"] = amr_summary[gene_col].apply(is_priority_gene)

    display(
        amr_summary
        .sort_values(["isolate_id", "priority_marker"], ascending=[True, False])
        .head(20)
    )

⚠️ amr_summary is empty.
This means AMRFinderPlus did not return/load any AMR hits.
Check the previous AMRFinder result files first.

In [7]:
# DEBUG: check AMRFinder output files
import glob, os, pandas as pd

files = glob.glob("amrfinder_results/*_amrfinder.tsv")
print("Number of AMRFinder result files:", len(files))

for f in files[:10]:
    print(f, "size:", os.path.getsize(f))

    try:
        temp = pd.read_csv(f, sep="\t")
        print("rows:", len(temp))
        print("columns:", temp.columns.tolist())
        display(temp.head())
    except Exception as e:
        print("Could not read:", e)

Number of AMRFinder result files: 0

In [8]:
# SAFE Cell 7: Flag clinically important AMR genes

priority_genes = [
    "blaKPC", "blaNDM", "blaOXA", "blaVIM", "blaIMP",
    "mcr", "mecA", "vanA", "vanB", "aac", "aph", "erm", "tet"
]

if amr_summary.empty:
    print("⚠️ amr_summary is empty.")
    print("This means AMRFinderPlus did not return/load any AMR hits.")
    print("Check the previous AMRFinder result files first.")
else:
    print("Columns available:")
    print(amr_summary.columns.tolist())

    gene_col = "Gene symbol" if "Gene symbol" in amr_summary.columns else None

    if gene_col is None:
        possible_gene_cols = [
            c for c in amr_summary.columns
            if "gene" in c.lower() or "symbol" in c.lower() or "element" in c.lower()
        ]
        print("Possible gene columns:", possible_gene_cols)

        if possible_gene_cols:
            gene_col = possible_gene_cols[0]
        else:
            raise ValueError("No gene-like column found in AMR summary.")

    def is_priority_gene(gene):
        gene = str(gene).lower()
        return any(pg.lower() in gene for pg in priority_genes)

    amr_summary["priority_marker"] = amr_summary[gene_col].apply(is_priority_gene)

    display(
        amr_summary
        .sort_values(["isolate_id", "priority_marker"], ascending=[True, False])
        .head(20)
    )

⚠️ amr_summary is empty.
This means AMRFinderPlus did not return/load any AMR hits.
Check the previous AMRFinder result files first.

In [9]:
import os, glob

print("Files in isolates folder:")
for f in glob.glob("isolates/*"):
    print(f, "size:", os.path.getsize(f))

Files in isolates folder:

In [10]:
!amrfinder -n isolates/YOUR_FILE_NAME.fasta -o test_amrfinder.tsv
!cat test_amrfinder.tsv

Running: amrfinder -n isolates/YOUR_FILE_NAME.fasta -o test_amrfinder.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
*** ERROR ***
No valid AMRFinder database is found.
This directory (or symbolic link to directory) is not found: /usr/local/share/amrfinderplus/data/latest
To download the latest version to the default directory run: amrfinder -u
cat: test_amrfinder.tsv: No such file or directory

In [11]:
!amrfinder -u

Running: amrfinder -u
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Running: /usr/local/bin/amrfinder_update -d /usr/local/share/amrfinderplus/data
Looking up the published databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
Looking for the target directory: /usr/local/share/amrfinderplus/data/2026-03-24.1/
Downloading AMRFinder database version 2026-03-24.1 into: /usr/local/share/amrfinderplus/data/2026-03-24.1/
Running: /usr/local/bin/amrfinder_index /usr/local/share/amrfinderplus/data/2026-03-24.1/
Indexing
amrfinder_index took 5 seconds to complete
amrfinder_update took 17 seconds to complete
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
amrfinder took 17 seconds to complete

In [13]:
!amrfinder_update

Running: amrfinder_update
Looking up the published databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
Looking for the target directory: /usr/local/bin/data/2026-03-24.1/
WARNING: /usr/local/bin/data/2026-03-24.1/: contains the latest version 2026-03-24.1
Skipping update
Use amrfinder --force_update to overwrite the existing database
amrfinder_update took 0 seconds to complete

In [14]:
!amrfinder --version
!ls /usr/local/share/amrfinderplus/data/latest

4.2.7
AMR_CDS.fa
AMR_CDS.fa.ndb
AMR_CDS.fa.nhr
AMR_CDS.fa.nin
AMR_CDS.fa.njs
AMR_CDS.fa.not
AMR_CDS.fa.nsq
AMR_CDS.fa.ntf
AMR_CDS.fa.nto
AMR_DNA-Acinetobacter_baumannii.fa
AMR_DNA-Acinetobacter_baumannii.fa.ndb
AMR_DNA-Acinetobacter_baumannii.fa.nhr
AMR_DNA-Acinetobacter_baumannii.fa.nin
AMR_DNA-Acinetobacter_baumannii.fa.njs
AMR_DNA-Acinetobacter_baumannii.fa.not
AMR_DNA-Acinetobacter_baumannii.fa.nsq
AMR_DNA-Acinetobacter_baumannii.fa.ntf
AMR_DNA-Acinetobacter_baumannii.fa.nto
AMR_DNA-Acinetobacter_baumannii.tsv
AMR_DNA-Bordetella_pertussis.fa
AMR_DNA-Bordetella_pertussis.fa.ndb
AMR_DNA-Bordetella_pertussis.fa.nhr
AMR_DNA-Bordetella_pertussis.fa.nin
AMR_DNA-Bordetella_pertussis.fa.njs
AMR_DNA-Bordetella_pertussis.fa.not
AMR_DNA-Bordetella_pertussis.fa.nsq
AMR_DNA-Bordetella_pertussis.fa.ntf
AMR_DNA-Bordetella_pertussis.fa.nto
AMR_DNA-Bordetella_pertussis.tsv
AMR_DNA-Campylobacter.fa
AMR_DNA-Campylobacter.fa.ndb
AMR_DNA-Campylobacter.fa.nhr
AMR_DNA-Campylobacter.fa.nin
AMR_DNA-Campylobacter.fa.njs
AMR_DNA-Campylobacter.fa.not
AMR_DNA-Campylobacter.fa.nsq
AMR_DNA-Campylobacter.fa.ntf
AMR_DNA-Campylobacter.fa.nto
AMR_DNA-Campylobacter.tsv
AMR_DNA-Clostridioides_difficile.fa
AMR_DNA-Clostridioides_difficile.fa.ndb
AMR_DNA-Clostridioides_difficile.fa.nhr
AMR_DNA-Clostridioides_difficile.fa.nin
AMR_DNA-Clostridioides_difficile.fa.njs
AMR_DNA-Clostridioides_difficile.fa.not
AMR_DNA-Clostridioides_difficile.fa.nsq
AMR_DNA-Clostridioides_difficile.fa.ntf
AMR_DNA-Clostridioides_difficile.fa.nto
AMR_DNA-Clostridioides_difficile.tsv
AMR_DNA-Enterococcus_faecalis.fa
AMR_DNA-Enterococcus_faecalis.fa.ndb
AMR_DNA-Enterococcus_faecalis.fa.nhr
AMR_DNA-Enterococcus_faecalis.fa.nin
AMR_DNA-Enterococcus_faecalis.fa.njs
AMR_DNA-Enterococcus_faecalis.fa.not
AMR_DNA-Enterococcus_faecalis.fa.nsq
AMR_DNA-Enterococcus_faecalis.fa.ntf
AMR_DNA-Enterococcus_faecalis.fa.nto
AMR_DNA-Enterococcus_faecalis.tsv
AMR_DNA-Enterococcus_faecium.fa
AMR_DNA-Enterococcus_faecium.fa.ndb
AMR_DNA-Enterococcus_faecium.fa.nhr
AMR_DNA-Enterococcus_faecium.fa.nin
AMR_DNA-Enterococcus_faecium.fa.njs
AMR_DNA-Enterococcus_faecium.fa.not
AMR_DNA-Enterococcus_faecium.fa.nsq
AMR_DNA-Enterococcus_faecium.fa.ntf
AMR_DNA-Enterococcus_faecium.fa.nto
AMR_DNA-Enterococcus_faecium.tsv
AMR_DNA-Escherichia.fa
AMR_DNA-Escherichia.fa.ndb
AMR_DNA-Escherichia.fa.nhr
AMR_DNA-Escherichia.fa.nin
AMR_DNA-Escherichia.fa.njs
AMR_DNA-Escherichia.fa.not
AMR_DNA-Escherichia.fa.nsq
AMR_DNA-Escherichia.fa.ntf
AMR_DNA-Escherichia.fa.nto
AMR_DNA-Escherichia.tsv
AMR_DNA-Klebsiella_oxytoca.fa
AMR_DNA-Klebsiella_oxytoca.fa.ndb
AMR_DNA-Klebsiella_oxytoca.fa.nhr
AMR_DNA-Klebsiella_oxytoca.fa.nin
AMR_DNA-Klebsiella_oxytoca.fa.njs
AMR_DNA-Klebsiella_oxytoca.fa.not
AMR_DNA-Klebsiella_oxytoca.fa.nsq
AMR_DNA-Klebsiella_oxytoca.fa.ntf
AMR_DNA-Klebsiella_oxytoca.fa.nto
AMR_DNA-Klebsiella_oxytoca.tsv
AMR_DNA-Klebsiella_pneumoniae.fa
AMR_DNA-Klebsiella_pneumoniae.fa.ndb
AMR_DNA-Klebsiella_pneumoniae.fa.nhr
AMR_DNA-Klebsiella_pneumoniae.fa.nin
AMR_DNA-Klebsiella_pneumoniae.fa.njs
AMR_DNA-Klebsiella_pneumoniae.fa.not
AMR_DNA-Klebsiella_pneumoniae.fa.nsq
AMR_DNA-Klebsiella_pneumoniae.fa.ntf
AMR_DNA-Klebsiella_pneumoniae.fa.nto
AMR_DNA-Klebsiella_pneumoniae.tsv
AMR_DNA-Neisseria_gonorrhoeae.fa
AMR_DNA-Neisseria_gonorrhoeae.fa.ndb
AMR_DNA-Neisseria_gonorrhoeae.fa.nhr
AMR_DNA-Neisseria_gonorrhoeae.fa.nin
AMR_DNA-Neisseria_gonorrhoeae.fa.njs
AMR_DNA-Neisseria_gonorrhoeae.fa.not
AMR_DNA-Neisseria_gonorrhoeae.fa.nsq
AMR_DNA-Neisseria_gonorrhoeae.fa.ntf
AMR_DNA-Neisseria_gonorrhoeae.fa.nto
AMR_DNA-Neisseria_gonorrhoeae.tsv
AMR_DNA-Salmonella.fa
AMR_DNA-Salmonella.fa.ndb
AMR_DNA-Salmonella.fa.nhr
AMR_DNA-Salmonella.fa.nin
AMR_DNA-Salmonella.fa.njs
AMR_DNA-Salmonella.fa.not
AMR_DNA-Salmonella.fa.nsq
AMR_DNA-Salmonella.fa.ntf
AMR_DNA-Salmonella.fa.nto
AMR_DNA-Salmonella.tsv
AMR_DNA-Staphylococcus_aureus.fa
AMR_DNA-Staphylococcus_aureus.fa.ndb
AMR_DNA-Staphylococcus_aureus.fa.nhr
AMR_DNA-Staphylococcus_aureus.fa.nin
AMR_DNA-Staphylococcus_aureus.fa.njs
AMR_DNA-Staphylococcus_aureus.fa.not
AMR_DNA-Staphylococcus_aureus.fa.nsq
AMR_DNA-Staphylococcus_aureus.fa.ntf
AMR_DNA-Staphylococcus_aureus.fa.nto
AMR_DNA-Staphylococcus_aureus.tsv
AMR_DNA-Streptococcus_pneumoniae.fa
AMR_DNA-Streptococcus_pneumoniae.fa.ndb
AMR_DNA-Streptococcus_pneumoniae.fa.nhr
AMR_DNA-Streptococcus_pneumoniae.fa.nin
AMR_DNA-Streptococcus_pneumoniae.fa.njs
AMR_DNA-Streptococcus_pneumoniae.fa.not
AMR_DNA-Streptococcus_pneumoniae.fa.nsq
AMR_DNA-Streptococcus_pneumoniae.fa.ntf
AMR_DNA-Streptococcus_pneumoniae.fa.nto
AMR_DNA-Streptococcus_pneumoniae.tsv
AMR.LIB
AMR.LIB.h3f
AMR.LIB.h3i
AMR.LIB.h3m
AMR.LIB.h3p
AMRProt.fa
AMRProt.fa.pdb
AMRProt.fa.phr
AMRProt.fa.pin
AMRProt.fa.pjs
AMRProt.fa.pot
AMRProt.fa.psq
AMRProt.fa.ptf
AMRProt.fa.pto
AMRProt-mutation.tsv
AMRProt-suppress.tsv
AMRProt-susceptible.fa
AMRProt-susceptible.tsv
changes.txt
database_format_version.txt
fam.tsv
taxgroup.tsv
version.txt

In [15]:
!amrfinder -n isolates/YOUR_FILE_NAME.fasta -o test_amrfinder.tsv
!cat test_amrfinder.tsv | head

Running: amrfinder -n isolates/YOUR_FILE_NAME.fasta -o test_amrfinder.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
*** ERROR ***
Cannot open file 'isolates/YOUR_FILE_NAME.fasta' to get file size
cat: test_amrfinder.tsv: No such file or directory

In [16]:
import glob, os

print(glob.glob("isolates/*"))

[]

In [17]:
from google.colab import files
import os, shutil

os.makedirs("isolates", exist_ok=True)

uploaded = files.upload()

for fn in uploaded.keys():
    shutil.move(fn, f"isolates/{fn}")

print(glob.glob("isolates/*"))

[]

In [18]:
!wget -O klebsiella.fna https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/240/185/GCF_000240185.1_ASM24018v1/GCF_000240185.1_ASM24018v1_genomic.fna

--2026-04-28 19:00:56--  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/240/185/GCF_000240185.1_ASM24018v1/GCF_000240185.1_ASM24018v1_genomic.fna
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.7, 130.14.250.10, 2607:f220:41e:250::13, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.7|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2026-04-28 19:00:57 ERROR 404: Not Found.

In [19]:
import os
os.makedirs("isolates", exist_ok=True)
!mv klebsiella.fna isolates/

In [20]:
!amrfinder -n isolates/klebsiella.fna -o test_amrfinder.tsv
!cat test_amrfinder.tsv | head -30

Running: amrfinder -n isolates/klebsiella.fna -o test_amrfinder.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
WARNING: Empty file: 'isolates/klebsiella.fna'
Making report
amrfinder took 0 seconds to complete
Protein id	Contig id	Start	Stop	Strand	Element symbol	Element name	Scope	Type	Subtype	Class	Subclass	Method	Target length	Reference sequence length	% Coverage of reference	% Identity to reference	Alignment length	Closest reference accession	Closest reference name	HMM accession	HMM description

In [21]:
# Remove empty file
!rm -f isolates/klebsiella.fna test_amrfinder.tsv

# Check folder
!ls -lh isolates

total 0

In [22]:
# Find AMRFinder test FASTA files available in Colab
!find /usr/local -name "*.fa" | head -20
!find /usr/local -name "*.fna" | head -20

/usr/local/bin/data/2026-03-24.1/AMR_DNA-Salmonella.fa
/usr/local/bin/data/2026-03-24.1/AMR_CDS.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Enterococcus_faecium.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Enterococcus_faecalis.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Neisseria_gonorrhoeae.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Clostridioides_difficile.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Escherichia.fa
/usr/local/bin/data/2026-03-24.1/AMRProt.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Bordetella_pertussis.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Staphylococcus_aureus.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Streptococcus_pneumoniae.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Acinetobacter_baumannii.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Campylobacter.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Klebsiella_pneumoniae.fa
/usr/local/bin/data/2026-03-24.1/AMR_DNA-Klebsiella_oxytoca.fa
/usr/local/bin/data/2026-03-24.1/AMRProt-susceptible.fa
/usr/local/share/easel/demotic/examples/example-single.fa
/usr/local/share/easel/demotic/examples/example.fa
/usr/local/share/easel/demotic/examples/example-single-psiquery.fa
/usr/local/share/amrfinderplus/data/2026-03-24.1/AMR_DNA-Salmonella.fa

In [24]:
# Use AMRFinder's own test DNA if available
!find /usr/local -name "test_dna.fa"

In [25]:
!rm -rf isolates
!mkdir isolates

!wget -O isolates/test_dna.fa https://raw.githubusercontent.com/ncbi/amr/master/test_dna.fa

!ls -lh isolates/test_dna.fa
!head isolates/test_dna.fa

--2026-04-28 19:07:33--  https://raw.githubusercontent.com/ncbi/amr/master/test_dna.fa
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32205 (31K) [text/plain]
Saving to: ‘isolates/test_dna.fa’

isolates/test_dna.f 100%[===================>]  31.45K  --.-KB/s    in 0.002s

2026-04-28 19:07:33 (17.9 MB/s) - ‘isolates/test_dna.fa’ saved [32205/32205]

-rw-r--r-- 1 root root 32K Apr 28 19:07 isolates/test_dna.fa
>contig01 blaTEM-156_cds
AACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGATACAATAACCCTGATAA
ATGCTTCAATAATATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTT
TTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCA
GTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCC
GAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTGTTGACG
CCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCAC
AGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAAC
ACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATAG
GGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGA

In [26]:
!amrfinder -n isolates/test_dna.fa -O Escherichia --plus -o test_amrfinder.tsv
!cat test_amrfinder.tsv | head -30

Running: amrfinder -n isolates/test_dna.fa -O Escherichia --plus -o test_amrfinder.tsv
The number of threads cannot be greater than 2 on this computer
The current number of threads is 4, reducing to 2
Software directory: /usr/local/bin/
Software version: 4.2.7
WARNING: This was compiled for running under bioconda, but $CONDA_PREFIX was not found
Reverting to hard coded directory: /usr/local/share/amrfinderplus/data/latest
Database directory: /usr/local/share/amrfinderplus/data/2026-03-24.1
Database version: 2026-03-24.1
AMRFinder translated nucleotide and mutation search
Running blastx
Running blastn
Running stxtyper
Making report
amrfinder took 9 seconds to complete
Protein id	Contig id	Start	Stop	Strand	Element symbol	Element name	Scope	Type	Subtype	Class	Subclass	Method	Target length	Reference sequence length	% Coverage of reference	% Identity to reference	Alignment length	Closest reference accession	Closest reference name	HMM accession	HMM description
NA	contig01	1	984	+	blaTEMp_G162T	Escherichia amoxicillin-clavulanic acid/piperacillin-tazobactam/ticarcillin-clavulanic acid resistant blaTEM promoter	core	AMR	POINT	BETA-LACTAM	AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOBACTAM/TICARCILLIN-CLAVULANIC_ACID	POINTN	984	1176	83.67	99.80	984	NZ_CP095603.1:148777-149952	blaTEM promoter region	NA	NA
NA	contig01	101	958	+	blaTEM-156	class A beta-lactamase TEM-156	core	AMR	AMR	BETA-LACTAM	BETA-LACTAM	ALLELEX	286	286	100.00	100.00	286	WP_061158039.1	class A beta-lactamase TEM-156	NA	NA
NA	contig02	1	1191	+	blaPDC	PDC family class C beta-lactamase	core	AMR	AMR	BETA-LACTAM	CEPHALOSPORIN	BLASTX	397	397	100.00	99.75	397	WP_061189306.1	class C beta-lactamase PDC-114	NA	NA
NA	contig03	101	802	+	blaOXA	OXA-48 family class D beta-lactamase	core	AMR	AMR	BETA-LACTAM	BETA-LACTAM	PARTIALX	234	265	88.30	100.00	234	WP_058842180.1	OXA-48 family carbapenem-hydrolyzing class D beta-lactamase OXA-436	NA	NA
NA	contig04	101	1147	+	vanG	D-alanine--D-serine ligase VanG	core	AMR	AMR	GLYCOPEPTIDE	VANCOMYCIN	EXACTX	349	349	100.00	100.00	349	WP_063856695.1	D-alanine--D-serine ligase VanG	NA	NA
NA	contig04	1261	2391	+	blaEC	BlaEC family class C beta-lactamase	plus	AMR	AMR	BETA-LACTAM	BETA-LACTAM	BLASTX	377	377	100.00	98.14	377	WP_063610930.1	extended-spectrum class C beta-lactamase EC-15	NA	NA
NA	contig08	1	700	+	blaTEMp_G162T	Escherichia amoxicillin-clavulanic acid/piperacillin-tazobactam/ticarcillin-clavulanic acid resistant blaTEM promoter	core	AMR	POINT	BETA-LACTAM	AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOBACTAM/TICARCILLIN-CLAVULANIC_ACID	POINTN	700	1176	59.52	99.71	700	NZ_CP095603.1:148777-149952	blaTEM promoter region	NA	NA
NA	contig08	101	700	+	blaTEM	TEM family class A beta-lactamase	core	AMR	AMR	BETA-LACTAM	BETA-LACTAM	PARTIAL_CONTIG_ENDX	200	286	69.93	100.00	200	WP_061158039.1	class A beta-lactamase TEM-156	NA	NA
NA	contig09	1	651	-	aph(3'')-Ib	aminoglycoside O-phosphotransferase APH(3'')-Ib	core	AMR	AMR	AMINOGLYCOSIDE	STREPTOMYCIN	PARTIAL_CONTIG_ENDX	217	267	81.27	100.00	217	WP_001082319.1	aminoglycoside O-phosphotransferase APH(3'')-Ib	NA	NA
NA	contig09	715	1377	-	sul2	sulfonamide-resistant dihydropteroate synthase Sul2	core	AMR	AMR	SULFONAMIDE	SULFONAMIDE	PARTIAL_CONTIG_ENDX	221	271	81.55	100.00	221	WP_001043265.1	sulfonamide-resistant dihydropteroate synthase Sul2	NA	NA
NA	contig10	486	1307	+	blaOXA	OXA-9 family oxacillin-hydrolyzing class D beta-lactamase	core	AMR	AMR	BETA-LACTAM	BETA-LACTAM	INTERNAL_STOP	274	274	100.00	99.64	274	WP_000722315.1	oxacillin-hydrolyzing class D beta-lactamase OXA-9	NA	NA
NA	contig11	1	984	+	blaTEMp_G162T	Escherichia amoxicillin-clavulanic acid/piperacillin-tazobactam/ticarcillin-clavulanic acid resistant blaTEM promoter	core	AMR	POINT	BETA-LACTAM	AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOBACTAM/TICARCILLIN-CLAVULANIC_ACID	POINTN	984	1176	83.67	96.04	984	NZ_CP095603.1:148777-149952	blaTEM promoter region	NA	NA
NA	contig11	101	958	+	blaTEM	TEM family class A beta-lactamase	core	AMR	AMR	BETA-LACTAM	BETA-LACTAM	INTERNAL_STOP	286	286	100.00	93.01	286	WP_061158039.1	class A beta-lactamase TEM-156	NA	NA
NA	contig12	71	634	+	qacR	multidrug-binding transcriptional regulator QacR	plus	STRESS	BIOCIDE	QUATERNARY AMMONIUM	QUATERNARY AMMONIUM	BLASTX	188	188	100.00	99.47	188	ADK23698.1	multidrug-binding transcriptional regulator QacR	NA	NA
NA	contig13	1	1137	+	emrD3	multidrug efflux MFS transporter EmrD-3	plus	AMR	AMR	EFFLUX	EFFLUX	EXACTX	379	379	100.00	100.00	379	ABQ18953.1	multidrug efflux MFS transporter EmrD-3	NA	NA
NA	contig14	1	1089	+	pmrB_C84R	Escherichia colistin resistant PmrB	core	AMR	POINT	COLISTIN	COLISTIN	POINTX	363	363	100.00	99.72	363	WP_001300761.1	two-component system sensor histidine kinase PmrB	NA	NA
NA	contig14	1093	2181	+	pmrB_C84R	Escherichia colistin resistant PmrB	core	AMR	POINT	COLISTIN	COLISTIN	POINTX	363	363	100.00	99.72	363	WP_001300761.1	two-component system sensor histidine kinase PmrB	NA	NA
NA	contig15	1	2905	+	23S_A2058T	Escherichia azithromycin/erythromycin/telithromycin resistant 23S	core	AMR	POINT	MACROLIDE	AZITHROMYCIN/ERYTHROMYCIN/TELITHROMYCIN	POINTN	2905	2905	100.00	99.97	2905	NC_004431.1:237160-240064	23S ribosomal RNA	NA	NA
NA	contig16	1	720	+	nfsA_K141Ter	Escherichia nitrofurantoin resistant NfsA	core	AMR	POINT	NITROFURAN	NITROFURANTOIN	POINTX	240	240	100.00	99.17	240	WP_089631889.1	nitroreductase NfsA	NA	NA
NA	contig16	1	720	+	nfsA_R15C	Escherichia nitrofurantoin resistant NfsA	core	AMR	POINT	NITROFURAN	NITROFURANTOIN	POINTX	240	240	100.00	99.17	240	WP_089631889.1	nitroreductase NfsA	NA	NA
NA	contig17	1	247	+	ampC_T-14TGT	Escherichia cephalosporin resistant ampC promoter	core	AMR	POINT	BETA-LACTAM	CEPHALOSPORIN	POINTN	247	245	100.00	99.19	247	NZ_CP041538.1:1149245-1149489	ampC/blaEC promoter region	NA	NA
NA	contig18	279	1235	+	stxA2	Shiga toxin Stx2 subunit A	plus	VIRULENCE	VIRULENCE	STX2	stxA2	EXACTX	319	319	100.00	100.00	319	TJA36680.1	Shiga toxin Stx2 subunit A	NA	NA
NA	contig18	279	1516	+	stx2a_operon	stx2a operon	plus	VIRULENCE	STX_TYPE	STX2	STX2A	COMPLETE	1238	NA	NA	100.00	408	AAS07600.1,AAM90978.1	Shiga toxin stx2a	NA	NA
NA	contig18	1250	1516	+	stxB2	Shiga toxin Stx2a subunit B	plus	VIRULENCE	VIRULENCE	STX2	stxB2a	EXACTX	89	89	100.00	100.00	89	AAM90978.1	Shiga toxin Stx2a subunit B	NA	NA

In [27]:
import pandas as pd

# Load AMRFinder output
amr_df = pd.read_csv("test_amrfinder.tsv", sep="\t")

# Extract gene symbols
gene_col = "Element symbol"

detected_genes = amr_df[gene_col].dropna().unique().tolist()

print("Detected AMR genes:")
for g in detected_genes:
    print(g)

Detected AMR genes:
blaTEMp_G162T
blaTEM-156
blaPDC
blaOXA
vanG
blaEC
blaTEM
aph(3'')-Ib
sul2
qacR
emrD3
pmrB_C84R
23S_A2058T
nfsA_K141Ter
nfsA_R15C
ampC_T-14TGT
stxA2
stx2a_operon
stxB2

In [28]:
target_genes = ["blaKPC", "blaNDM", "mcr", "mecA", "blaOXA", "blaTEM"]

In [29]:
def match_target_gene(gene):
    gene = gene.lower()
    return any(t.lower() in gene for t in target_genes)

amr_df["crispr_target"] = amr_df[gene_col].apply(match_target_gene)

amr_targets = amr_df[amr_df["crispr_target"] == True]

amr_targets[[gene_col, "Class", "Subclass"]]

,Element symbol,Class,Subclass
0,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...
1,blaTEM-156,BETA-LACTAM,BETA-LACTAM
3,blaOXA,BETA-LACTAM,BETA-LACTAM
6,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...
7,blaTEM,BETA-LACTAM,BETA-LACTAM
10,blaOXA,BETA-LACTAM,BETA-LACTAM
11,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...
12,blaTEM,BETA-LACTAM,BETA-LACTAM

In [30]:
# Normalize gene names (important)
amr_targets["clean_gene"] = amr_targets["Element symbol"].str.replace(r'[^a-zA-Z0-9]', '', regex=True).str.lower()

amr_targets[["Element symbol", "clean_gene"]]

/tmp/ipykernel_36292/3621329773.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amr_targets["clean_gene"] = amr_targets["Element symbol"].str.replace(r'[^a-zA-Z0-9]', '', regex=True).str.lower()

   Element symbol    clean_gene
0   blaTEMp_G162T  blatempg162t
1      blaTEM-156     blatem156
3          blaOXA        blaoxa
6   blaTEMp_G162T  blatempg162t
7          blaTEM        blatem
10         blaOXA        blaoxa
11  blaTEMp_G162T  blatempg162t
12         blaTEM        blatem

In [31]:
from google.colab import files
uploaded = files.upload()

Saving cross_model_reference_ranked_guides.csv to cross_model_reference_ranked_guides.csv

In [32]:
import pandas as pd

crispr_df = pd.read_csv("cross_model_reference_ranked_guides.csv")

print(crispr_df.columns)
crispr_df.head()

Index(['gene', 'position', 'strand', 'spacer', 'pam', 'gc_content',
       'on_target_score', 'offtarget_hits_0mm', 'offtarget_hits_1mm',
       'offtarget_hits_2mm', 'offtarget_hits_3mm', 'offtarget_penalty',
       'specificity_score', 'total_strains', 'perfect_match_strains',
       'one_mismatch_or_better_strains', 'pam_supported_strains',
       'perfect_match_fraction', 'one_mismatch_or_better_fraction',
       'pam_supported_fraction', 'conservation_score', 'mean_strain_score',
       'min_strain_score', 'std_strain_score', 'final_score', 'classification',
       'guide_key', 'weight_scheme', 'final_score_new', 'classification_new',
       'rank_on_target', 'rank_off_target', 'rank_conservation', 'rank_final',
       'consensus_score', 'rank_consensus'],
      dtype='object')

,gene,position,strand,spacer,pam,gc_content,on_target_score,offtarget_hits_0mm,offtarget_hits_1mm,offtarget_hits_2mm,...,guide_key,weight_scheme,final_score_new,classification_new,rank_on_target,rank_off_target,rank_conservation,rank_final,consensus_score,rank_consensus
0,blaKPC,171,+,AGAGCCTTACTGCCCGAAGG,CGG,60.0,82.0,0,0,0,...,blaKPC|171|AGAGCCTTACTGCCCGAAGG,40/30/30,92.8,Excellent,3.0,1.0,1.0,3.0,94.0,3.0
1,blaKPC,174,+,GCCTTACTGCCCGAAGGCGG,CGG,70.0,82.0,0,0,0,...,blaKPC|174|GCCTTACTGCCCGAAGGCGG,40/30/30,92.8,Excellent,3.0,1.0,1.0,3.0,94.0,3.0
2,blaKPC,248,+,CGGCTCCATCGGTGTGTACG,CGG,65.0,82.0,0,0,0,...,blaKPC|248|CGGCTCCATCGGTGTGTACG,40/30/30,92.8,Excellent,3.0,1.0,1.0,3.0,94.0,3.0
3,blaKPC,282,-,AGCGACGGAATAGTGTATGG,CGG,50.0,82.0,0,0,0,...,blaKPC|282|AGCGACGGAATAGTGTATGG,40/30/30,92.8,Excellent,3.0,1.0,1.0,3.0,94.0,3.0
4,blaKPC,205,-,AGCGACGGAATAGTGTATGG,CGG,50.0,82.0,0,0,0,...,blaKPC|205|AGCGACGGAATAGTGTATGG,40/30/30,92.8,Excellent,3.0,1.0,1.0,3.0,94.0,3.0

In [33]:
crispr_df["clean_gene"] = crispr_df["gene"].str.replace(r'[^a-zA-Z0-9]', '', regex=True).str.lower()

In [34]:
final_df = amr_targets.merge(
    crispr_df,
    on="clean_gene",
    how="left"
)

final_df.head()

,Protein id,Contig id,Start,Stop,Strand,Element symbol,Element name,Scope,Type,Subtype,...,guide_key,weight_scheme,final_score_new,classification_new,rank_on_target,rank_off_target,rank_conservation,rank_final,consensus_score,rank_consensus
0,NaN,contig01,1,984,+,blaTEMp_G162T,Escherichia amoxicillin-clavulanic acid/pipera...,core,AMR,POINT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,contig01,101,958,+,blaTEM-156,class A beta-lactamase TEM-156,core,AMR,AMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,contig03,101,802,+,blaOXA,OXA-48 family class D beta-lactamase,core,AMR,AMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,contig08,1,700,+,blaTEMp_G162T,Escherichia amoxicillin-clavulanic acid/pipera...,core,AMR,POINT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,contig08,101,700,+,blaTEM,TEM family class A beta-lactamase,core,AMR,AMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
print("AMR genes:", amr_targets["clean_gene"].unique())
print("CRISPR genes:", crispr_df["clean_gene"].unique())

AMR genes: ['blatempg162t' 'blatem156' 'blaoxa' 'blatem']
CRISPR genes: ['blakpc' 'blandm1' 'mcr1' 'meca']

In [36]:
final_df = final_df.sort_values(
    ["clean_gene", "final_score"],
    ascending=[True, False]
)

final_df["rank"] = final_df.groupby("clean_gene").cumcount() + 1

top_guides = final_df[final_df["rank"] <= 5]

In [37]:
camda_output = top_guides[[
    "clean_gene",
    "Element symbol",
    "Class",
    "Subclass",
    "spacer",
    "pam",
    "final_score",
    "rank"
]]

camda_output.head(20)

,clean_gene,Element symbol,Class,Subclass,spacer,pam,final_score,rank
2,blaoxa,blaOXA,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
5,blaoxa,blaOXA,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,2
4,blatem,blaTEM,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
7,blatem,blaTEM,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,2
1,blatem156,blaTEM-156,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
0,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,1
3,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,2
6,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,3

In [38]:
camda_output.to_csv("CAMDA_AMR_CRISPR_output.csv", index=False)

from google.colab import files
files.download("CAMDA_AMR_CRISPR_output.csv")

In [39]:
"final_score"

'final_score'

In [40]:
import pandas as pd

df = pd.read_csv("CAMDA_AMR_CRISPR_output.csv")

print(df.shape)
df.head(10)

(8, 8)

,clean_gene,Element symbol,Class,Subclass,spacer,pam,final_score,rank
0,blaoxa,blaOXA,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
1,blaoxa,blaOXA,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,2
2,blatem,blaTEM,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
3,blatem,blaTEM,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,2
4,blatem156,blaTEM-156,BETA-LACTAM,BETA-LACTAM,NaN,NaN,NaN,1
5,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,1
6,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,2
7,blatempg162t,blaTEMp_G162T,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,NaN,NaN,NaN,3

In [41]:
print(df.columns)
print(df["clean_gene"].unique())

Index(['clean_gene', 'Element symbol', 'Class', 'Subclass', 'spacer', 'pam',
       'final_score', 'rank'],
      dtype='object')
['blaoxa' 'blatem' 'blatem156' 'blatempg162t']

In [42]:
print("AMR genes:")
print(amr_targets["clean_gene"].unique())

print("CRISPR genes:")
print(crispr_df["clean_gene"].unique())

AMR genes:
['blatempg162t' 'blatem156' 'blaoxa' 'blatem']
CRISPR genes:
['blakpc' 'blandm1' 'mcr1' 'meca']

In [43]:
gene_map = {
    "blaoxa": "blaoxa",
    "blatem": "blatem",
    "blatem156": "blatem",
    "blatempg162t": "blatem"
}

amr_targets["mapped_gene"] = amr_targets["clean_gene"].map(gene_map)

crispr_df["mapped_gene"] = crispr_df["clean_gene"]

final_df = amr_targets.merge(
    crispr_df,
    on="mapped_gene",
    how="left"
)

final_df[["Element symbol", "mapped_gene", "spacer", "pam", "final_score"]].head(20)

/tmp/ipykernel_36292/2761722838.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amr_targets["mapped_gene"] = amr_targets["clean_gene"].map(gene_map)

  Element symbol mapped_gene spacer  pam  final_score
0  blaTEMp_G162T      blatem    NaN  NaN          NaN
1     blaTEM-156      blatem    NaN  NaN          NaN
2         blaOXA      blaoxa    NaN  NaN          NaN
3  blaTEMp_G162T      blatem    NaN  NaN          NaN
4         blaTEM      blatem    NaN  NaN          NaN
5         blaOXA      blaoxa    NaN  NaN          NaN
6  blaTEMp_G162T      blatem    NaN  NaN          NaN
7         blaTEM      blatem    NaN  NaN          NaN

In [44]:
from Bio import SeqIO
from Bio.Seq import Seq
import pandas as pd, re

records = list(SeqIO.parse("isolates/test_dna.fa", "fasta"))

def gc(seq):
    return round((seq.count("G") + seq.count("C")) / len(seq), 3)

guides = []

for _, row in amr_targets.iterrows():
    contig = row["Contig id"]
    start = int(row["Start"])
    stop = int(row["Stop"])
    gene = row["Element symbol"]

    rec = next(r for r in records if r.id == contig)
    seq = str(rec.seq).upper()[min(start, stop)-1:max(start, stop)]

    for i in range(len(seq)-23):
        spacer = seq[i:i+20]
        pam = seq[i+20:i+23]

        if re.match("^[ATGC]{20}$", spacer) and re.match("^[ATGC]GG$", pam):
            score = 1 - abs(gc(spacer)-0.5)
            guides.append({
                "gene": gene,
                "clean_gene": row["clean_gene"],
                "Class": row["Class"],
                "Subclass": row["Subclass"],
                "spacer": spacer,
                "pam": pam,
                "gc_content": gc(spacer),
                "final_score": round(score, 4)
            })

guide_df = pd.DataFrame(guides)

guide_df = guide_df.sort_values(
    ["clean_gene", "final_score"],
    ascending=[True, False]
)

guide_df["rank"] = guide_df.groupby("clean_gene").cumcount() + 1

camda_fixed = guide_df[guide_df["rank"] <= 5]

camda_fixed.to_csv("CAMDA_FINAL_FIXED_OUTPUT.csv", index=False)

camda_fixed.head(20)

,gene,clean_gene,Class,Subclass,spacer,pam,gc_content,final_score,rank
108,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,AGCCTTATCGGCTGTGTTGA,TGG,0.5,1.0,1
110,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,AACGATGATTGGCATGCCTG,CGG,0.5,1.0,2
116,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,CGAACATAAAACCCAAGGCG,TGG,0.5,1.0,3
118,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,CTGGAACGAGAATACACAGC,AGG,0.5,1.0,4
140,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,GACAGTTTTTGGCTCGATGG,TGG,0.5,1.0,5
185,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,1
190,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,ACGAGTGGGTTACATCGAAC,TGG,0.5,1.0,2
194,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,GTATTATCCCGTGTTGACGC,CGG,0.5,1.0,3
195,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TATTATCCCGTGTTGACGCC,GGG,0.5,1.0,4
325,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,5
56,blaTEM-156,blatem156,BETA-LACTAM,BETA-LACTAM,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,1
61,blaTEM-156,blatem156,BETA-LACTAM,BETA-LACTAM,ACGAGTGGGTTACATCGAAC,TGG,0.5,1.0,2
65,blaTEM-156,blatem156,BETA-LACTAM,BETA-LACTAM,GTATTATCCCGTGTTGACGC,CGG,0.5,1.0,3
66,blaTEM-156,blatem156,BETA-LACTAM,BETA-LACTAM,TATTATCCCGTGTTGACGCC,GGG,0.5,1.0,4
88,blaTEM-156,blatem156,BETA-LACTAM,BETA-LACTAM,ATGGAGGCGGATAAAGTTGC,AGG,0.5,1.0,5
2,blaTEMp_G162T,blatempg162t,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,1
7,blaTEMp_G162T,blatempg162t,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,ACGAGTGGGTTACATCGAAC,TGG,0.5,1.0,2
11,blaTEMp_G162T,blatempg162t,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,GTATTATCCCGTGTTGACGC,CGG,0.5,1.0,3
12,blaTEMp_G162T,blatempg162t,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,TATTATCCCGTGTTGACGCC,GGG,0.5,1.0,4
34,blaTEMp_G162T,blatempg162t,BETA-LACTAM,AMOXICILLIN-CLAVULANIC_ACID/PIPERACILLIN-TAZOB...,ATGGAGGCGGATAAAGTTGC,AGG,0.5,1.0,5

In [45]:
from google.colab import files
files.download("CAMDA_FINAL_FIXED_OUTPUT.csv")

In [46]:
import pandas as pd

df = pd.read_csv("CAMDA_FINAL_FIXED_OUTPUT.csv")

print(df.shape)
df.head(10)

(20, 9)

,gene,clean_gene,Class,Subclass,spacer,pam,gc_content,final_score,rank
0,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,AGCCTTATCGGCTGTGTTGA,TGG,0.5,1.0,1
1,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,AACGATGATTGGCATGCCTG,CGG,0.5,1.0,2
2,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,CGAACATAAAACCCAAGGCG,TGG,0.5,1.0,3
3,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,CTGGAACGAGAATACACAGC,AGG,0.5,1.0,4
4,blaOXA,blaoxa,BETA-LACTAM,BETA-LACTAM,GACAGTTTTTGGCTCGATGG,TGG,0.5,1.0,5
5,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,1
6,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,ACGAGTGGGTTACATCGAAC,TGG,0.5,1.0,2
7,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,GTATTATCCCGTGTTGACGC,CGG,0.5,1.0,3
8,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TATTATCCCGTGTTGACGCC,GGG,0.5,1.0,4
9,blaTEM,blatem,BETA-LACTAM,BETA-LACTAM,TTTTGCTCACCCAGAAACGC,TGG,0.5,1.0,5

In [47]:
df["isolate_id"] = "test_isolate_1"

df = df[[
    "isolate_id",
    "clean_gene",
    "gene",
    "Class",
    "Subclass",
    "spacer",
    "pam",
    "final_score",
    "rank"
]]

df.to_csv("CAMDA_FINAL_SUBMISSION.csv", index=False)